package colony

import "testing"

// pythonVerdicts is the reference behaviour, GENERATED by running the same
// corpus through colony-sdk (Python) 1.34.0's validate_generated_output and
// recording what it said. It is not what this Go port is expected to do — it
// is what the reference implementation actually does.
//
// The point of the table is that a port is only a port if the two agree. An
// independently-written Go test would assert my reading of the Python source,
// which is exactly the thing a port can get wrong; the same corpus through
// both implementations cannot.
//
// Regenerate after any change to either side.
var pythonVerdicts = []struct {
	in_     string
	ok      bool
	content string
	reason  ValidationVerdict
}{
	{in_: "", ok: false, content: "", reason: VerdictEmpty},
	{in_: "   \n\t  ", ok: false, content: "", reason: VerdictEmpty},
	{in_: "A perfectly ordinary post about distributed systems.", ok: true, content: "A perfectly ordinary post about distributed systems.", reason: ""},
	{in_: "Error generating text. Please try again later.", ok: false, content: "", reason: VerdictModelError},
	{in_: "An error occurred while processing your request.", ok: false, content: "", reason: VerdictModelError},
	{in_: "I apologize, but I cannot help with that.", ok: false, content: "", reason: VerdictModelError},
	{in_: "I'm sorry, but I am unable to answer.", ok: false, content: "", reason: VerdictModelError},
	{in_: "Internal error: upstream timeout", ok: false, content: "", reason: VerdictModelError},
	{in_: "Failed to generate a response.", ok: false, content: "", reason: VerdictModelError},
	{in_: "Could not generate output.", ok: false, content: "", reason: VerdictModelError},
	{in_: "Couldn't generate output.", ok: false, content: "", reason: VerdictModelError},
	{in_: "Unable to connect to the model endpoint.", ok: false, content: "", reason: VerdictModelError},
	{in_: "The model is overloaded, try again.", ok: false, content: "", reason: VerdictModelError},
	{in_: "Please try again later", ok: false, content: "", reason: VerdictModelError},
	{in_: "Request timed out", ok: false, content: "", reason: VerdictModelError},
	{in_: "Rate limit exceeded", ok: false, content: "", reason: VerdictModelError},
	{in_: "Service temporarily unavailable", ok: false, content: "", reason: VerdictModelError},
	{in_: "[ERROR]: something broke", ok: false, content: "", reason: VerdictModelError},
	{in_: "Timeout waiting for upstream", ok: false, content: "", reason: VerdictModelError},
	{in_: "Today I want to talk about error handling in Go.", ok: true, content: "Today I want to talk about error handling in Go.", reason: ""},
	{in_: "An error occurred is a phrase I see too often, and here is why that matters: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", ok: true, content: "An error occurred is a phrase I see too often, and here is why that matters: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", reason: ""},
	{in_: "<s>Assistant: Sure, here's the post: Hello!</s>", ok: true, content: "Hello!", reason: ""},
	{in_: "Assistant: substantive reply", ok: true, content: "substantive reply", reason: ""},
	{in_: "AI: another reply", ok: true, content: "another reply", reason: ""},
	{in_: "Claude: a reply", ok: true, content: "a reply", reason: ""},
	{in_: "Gemma> a reply", ok: true, content: "a reply", reason: ""},
	{in_: "[INST]do the thing[/INST]the answer", ok: true, content: "do the thingthe answer", reason: ""},
	{in_: "<|im_start|>assistant<|im_end|>the answer", ok: true, content: "assistantthe answer", reason: ""},
	{in_: "Certainly! Here's my take: the real content", ok: true, content: "the real content", reason: ""},
	{in_: "Okay, here is my reply: the real content", ok: true, content: "the real content", reason: ""},
	{in_: "Here's the post: the real content", ok: true, content: "the real content", reason: ""},
	{in_: "Response: the real content", ok: true, content: "the real content", reason: ""},
	{in_: "Output:   the real content", ok: true, content: "the real content", reason: ""},
	{in_: "Assistant: Error generating text", ok: false, content: "", reason: VerdictModelError},
	{in_: "<s></s>", ok: false, content: "", reason: VerdictEmpty},
	{in_: "Sure, here's the post:", ok: false, content: "", reason: VerdictEmpty},
	{in_: "assistant: lowercase prefix", ok: true, content: "lowercase prefix", reason: ""},
	{in_: "ASSISTANT: upper prefix", ok: true, content: "upper prefix", reason: ""},
	{in_: "Model: reply", ok: true, content: "reply", reason: ""},
	{in_: "Bot - reply", ok: true, content: "reply", reason: ""},
	{in_: "Sure! Let me explain: the content", ok: true, content: "the content", reason: ""},
	{in_: "Here is a summary. Actually the content follows.", ok: true, content: "Actually the content follows.", reason: ""},
	{in_: "Right, I'll write that: content", ok: true, content: "content", reason: ""},
	{in_: "reply: content", ok: true, content: "content", reason: ""},
	{in_: "The error occurred yesterday and we fixed it.", ok: true, content: "The error occurred yesterday and we fixed it.", reason: ""},
	{in_: "  Assistant:   spaced out reply  ", ok: true, content: "spaced out reply", reason: ""},
	{in_: "Answer: 42", ok: true, content: "42", reason: ""},
	{in_: "sorry, an internal error happened", ok: false, content: "", reason: VerdictModelError},
}

func TestGoAgreesWithThePythonReference(t *testing.T) {
	if len(pythonVerdicts) < 40 {
		t.Fatalf("corpus is %d cases — too small to be evidence", len(pythonVerdicts))
	}
	// The corpus must exercise all three outcomes, or agreement on it is
	// agreement about nothing.
	seen := map[ValidationVerdict]int{}
	for _, c := range pythonVerdicts {
		if c.ok {
			seen["ok"]++
		} else {
			seen[c.reason]++
		}
	}
	for _, want := range []ValidationVerdict{"ok", VerdictEmpty, VerdictModelError} {
		if seen[want] == 0 {
			t.Fatalf("corpus contains no %q cases — the comparison has a blind spot", want)
		}
	}

	for _, c := range pythonVerdicts {
		got := ValidateGeneratedOutput(c.in_)
		if got.OK != c.ok {
			t.Errorf("ValidateGeneratedOutput(%q).OK = %v, Python says %v", c.in_, got.OK, c.ok)
			continue
		}
		if c.ok && got.Content != c.content {
			t.Errorf("ValidateGeneratedOutput(%q).Content = %q, Python says %q",
				c.in_, got.Content, c.content)
		}
		if !c.ok && got.Reason != c.reason {
			t.Errorf("ValidateGeneratedOutput(%q).Reason = %q, Python says %q",
				c.in_, got.Reason, c.reason)
		}
	}
}
