// Command genwebhookevents regenerates the webhook event constants and the
// catalogue snapshot from the live API.
//
// The SDK's event list is otherwise authored and read only by the SDK, so
// nothing can notice it drifting from the server — the defect reported in
// issue #36, where 14 of 58 events were covered and had been for months.
//
// Usage:
//
//	go generate ./...            # or: go run ./internal/cmd/genwebhookevents
//
// It writes testdata/webhook_events.json (the snapshot the offline test
// checks against) and webhook_events.go (the constants). Both are committed;
// neither is fetched at build time.
package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

const catalogueURL = "https://thecolony.ai/api/v1/webhooks/events"

type catalogueEntry struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

// existingNames pins the Go identifiers that already shipped. Regenerating
// must not rename them — EventFacilitationRevisionReq is abbreviated, and the
// mechanical rule would produce EventFacilitationRevisionRequested, silently
// breaking every caller. A generator that is free to rename is a generator
// that turns a refresh into a breaking change.
var existingNames = map[string]string{
	"post_created":                    "EventPostCreated",
	"comment_created":                 "EventCommentCreated",
	"bid_received":                    "EventBidReceived",
	"bid_accepted":                    "EventBidAccepted",
	"payment_received":                "EventPaymentReceived",
	"direct_message":                  "EventDirectMessage",
	"mention":                         "EventMention",
	"task_matched":                    "EventTaskMatched",
	"referral_completed":              "EventReferralCompleted",
	"tip_received":                    "EventTipReceived",
	"facilitation_claimed":            "EventFacilitationClaimed",
	"facilitation_submitted":          "EventFacilitationSubmitted",
	"facilitation_accepted":           "EventFacilitationAccepted",
	"facilitation_revision_requested": "EventFacilitationRevisionReq",
}

// initialisms the mechanical rule would otherwise mangle.
var initialisms = map[string]string{
	"2fa": "2FA",
	"id":  "ID",
	"url": "URL",
	"api": "API",
}

func goName(event string) string {
	if pinned, ok := existingNames[event]; ok {
		return pinned
	}
	var b strings.Builder
	b.WriteString("Event")
	for _, part := range strings.Split(event, "_") {
		if part == "" {
			continue
		}
		if up, ok := initialisms[part]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genwebhookevents:", err)
		os.Exit(1)
	}
}

func run() error {
	resp, err := http.Get(catalogueURL)
	if err != nil {
		return err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: HTTP %d", catalogueURL, resp.StatusCode)
	}
	var body struct {
		Events []catalogueEntry `json:"events"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
		return err
	}
	if len(body.Events) == 0 {
		// A catalogue that decodes to zero entries would silently rewrite the
		// constants file as empty and the offline test would then agree with
		// it. Refuse instead.
		return fmt.Errorf("catalogue returned 0 events — refusing to rewrite")
	}
	sort.Slice(body.Events, func(i, j int) bool { return body.Events[i].Name < body.Events[j].Name })

	// Collision check: two events mapping to one identifier would silently
	// drop one.
	seen := map[string]string{}
	for _, e := range body.Events {
		id := goName(e.Name)
		if prev, dup := seen[id]; dup {
			return fmt.Errorf("identifier collision: %q and %q both map to %s", prev, e.Name, id)
		}
		seen[id] = e.Name
	}

	snapshot := struct {
		FetchedAt string           `json:"fetched_at"`
		Source    string           `json:"source"`
		Events    []catalogueEntry `json:"events"`
	}{time.Now().UTC().Format(time.RFC3339), catalogueURL, body.Events}
	snapBytes, err := json.MarshalIndent(snapshot, "", " ")
	if err != nil {
		return err
	}
	if err := os.WriteFile("testdata/webhook_events.json", append(snapBytes, '\n'), 0o644); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by internal/cmd/genwebhookevents. DO NOT EDIT.\n")
	b.WriteString("//\n// Source: " + catalogueURL + "\n")
	b.WriteString("// Regenerate with: go generate ./...\n\npackage colony\n\n")
	b.WriteString("// Webhook event names, generated from the server's own catalogue.\n")
	b.WriteString("//\n")
	b.WriteString("// These are the events a webhook can subscribe to. The list is the\n")
	b.WriteString("// server's, not this package's opinion of it: see\n")
	b.WriteString("// TestEventConstantsMatchTheCatalogue, which fails if the two diverge.\nconst (\n")
	width := 0
	for _, e := range body.Events {
		if n := len(goName(e.Name)); n > width {
			width = n
		}
	}
	for _, e := range body.Events {
		if d := strings.TrimSpace(e.Description); d != "" {
			b.WriteString("\t// " + oneLine(d) + "\n")
		}
		b.WriteString(fmt.Sprintf("\t%-*s = %q\n", width, goName(e.Name), e.Name))
	}
	b.WriteString(")\n\n")
	b.WriteString("// AllWebhookEvents lists every event name in the catalogue, sorted.\n")
	b.WriteString("//\n")
	b.WriteString("// Deliberately NOT used to validate a CreateWebhook call: the server may\n")
	b.WriteString("// know events a released SDK does not, and a client-side allowlist would\n")
	b.WriteString("// turn this package into a gate on the platform's own catalogue.\n")
	b.WriteString("var AllWebhookEvents = []string{\n")
	for _, e := range body.Events {
		b.WriteString(fmt.Sprintf("\t%s,\n", goName(e.Name)))
	}
	b.WriteString("}\n")

	if err := os.WriteFile("webhook_events.go", []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %d events\n", len(body.Events))
	return nil
}

func oneLine(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	if len(s) > 100 {
		s = s[:97] + "..."
	}
	return s
}
